/**
 * Build supabase/deploy/02_schema.sql: every file in supabase/migrations/ concatenated in
 * numeric order, for applying a whole schema in one paste in the Supabase SQL editor.
 *
 * The migrations are the source of truth. Edit those and re-run this; never hand-edit the
 * bundle, or the next build silently discards the edit.
 *
 * Two transforms are applied on the way out, because a bundle gets pasted more than once:
 *
 *  1. Every `create policy` is preceded by a `drop policy if exists` for the same name. Ten
 *     policy names are created twice across the migration history, and policies on the
 *     `storage` and `auth` schemas survive `drop schema public cascade`, so a re-run hit
 *     42710 "policy already exists" and stopped partway through.
 *  2. The same for the trigger on auth.users, which survives for the same reason.
 *
 * These belong here rather than in the migrations: a migration is applied once, in order, on
 * a database in a known state. The bundle has neither guarantee.
 *
 * Run: node supabase/deploy/build.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const migrationsDir = resolve(__dirname, '..', 'migrations')
const outFile = resolve(__dirname, '02_schema.sql')

const files = readdirSync(migrationsDir).filter(f => f.endsWith('.sql')).sort()

const rule = '-- ' + '─'.repeat(45)
let sql = `-- station-portal schema: migrations ${files[0].slice(0, 3)}..${files.at(-1).slice(0, 3)} concatenated, in order.\n`
sql += '-- GENERATED by supabase/deploy/build.mjs. Do not edit; edit the migrations and rebuild.\n'
sql += '-- Run in one paste in the Supabase SQL editor.\n'
for (const f of files) {
  sql += `\n\n${rule}\n-- ${f}\n${rule}\n\n` + readFileSync(resolve(migrationsDir, f), 'utf8')
}

/** Insert `line` at the start of the line containing index `at`, unless already guarded. */
function guard(text, pattern, makeDrop, isGuarded) {
  const out = []
  let last = 0
  let added = 0
  for (const m of [...text.matchAll(pattern)]) {
    const back = text.slice(Math.max(0, m.index - 250), m.index)
    if (isGuarded(back, m)) continue
    const lineStart = text.lastIndexOf('\n', m.index) + 1
    out.push(text.slice(last, lineStart), makeDrop(m) + '\n')
    last = lineStart
    added++
  }
  out.push(text.slice(last))
  return { text: out.join(''), added }
}

const policies = guard(
  sql,
  /create\s+policy\s+"([^"]+)"\s+on\s+([a-zA-Z_.]+)/gi,
  m => `drop policy if exists "${m[1]}" on ${m[2]};`,
  (back, m) => new RegExp(`drop\\s+policy\\s+if\\s+exists\\s+"${m[1].replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`, 'i').test(back),
)
sql = policies.text

const triggers = guard(
  sql,
  /create\s+trigger\s+([a-zA-Z_0-9]+)\s+[\s\S]{0,80}?\son\s+([a-zA-Z_.]+)/gi,
  m => `DROP TRIGGER IF EXISTS ${m[1]} ON ${m[2]};`,
  (back, m) => new RegExp(`drop\\s+trigger\\s+if\\s+exists\\s+${m[1]}`, 'i').test(back),
)
sql = triggers.text

writeFileSync(outFile, sql)

const tables = new Set([...sql.matchAll(/create\s+table\s+(?:if\s+not\s+exists\s+)?(?:public\.)?([a-zA-Z_0-9]+)/gi)].map(m => m[1].toLowerCase()))
console.log(`${files.length} migrations -> ${outFile}`)
console.log(`  ${sql.split('\n').length} lines, ${tables.size} tables`)
console.log(`  guarded ${policies.added} policies, ${triggers.added} triggers`)
